/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room.glb -t -T 
Files: room.glb [379.3KB] > /home/prankush1999/Code/MyRoom/public/room-transformed.glb [199.06KB] (48%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Chair: THREE.Mesh
    keyBoard_Buttons: THREE.Mesh
  }
  materials: {}
  // animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/room-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Chair.geometry} material={nodes.Chair.material} position={[0, 0.019, 0]} />
      <mesh geometry={nodes.keyBoard_Buttons.geometry} material={nodes.keyBoard_Buttons.material} />
    </group>
  )
}

useGLTF.preload('/room-transformed.glb')
