import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Three from "@/components/three";
import SmoothScrolling from "@/components/SmoothScrolling";
import { TransitionProviders } from "@/components/Transition";
import Controls from "@/components/Controls";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Three js Testing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SmoothScrolling>
        < TransitionProviders>
          {children}
        </TransitionProviders>
          </SmoothScrolling>
        <div className="top-0 flex sm:flex-row flex-col h-full w-full">

          <div className="fixed h-[60vh] sm:h-[100vh] w-[100vw] z-10 ">
            <Three />
          </div>
        <Controls />
        </div>
      </body>
    </html>
  );
}
